import { PortfolioData } from "./types";
import { FaRocket, FaUsers, FaTrophy, FaCode, FaBuilding, FaLightbulb } from "react-icons/fa";

export const nickname = "Ashiq.";
export const fullName = "Md Shoriful Islam Ashiq";
export const myPortfolioDomain = "https://ashiq.pro.bd";
export const midgenDomain = "https://midgen.ai";
export const midgenSoftwareLabsDomain = "https://midgenlabs.com";
export const personalEmail = "mdsiaofficial@gmail.com";
export const workEmail_Midgen = "ashiq@midgen.ai";
export const workEmail_MidgenLabs = "ashiq@midgenlabs.com";

export const portfolioData: PortfolioData = {
  basicInfo: {
    nickname: nickname,
    fullName: fullName,
    email: workEmail_Midgen,
    about: "Co-Founder & Operational Lead of Midgen leading AI-powered content creation platform with thousands of users globally. Passionate about scaling operations, building high-performing teams, and driving business growth through technology and strategic leadership.",
  },
  basicTitles: [
    "Co-Founder & COO",
    "Operations Leader",
    "Strategic Planner",
  ],
  featured: {
    company: "Midgen",
    tagline: "All-in-one AI Content Creation Platform",
    description: "Building tools that empower creators globally - Humanizer, Article Writer, AI Detector, and more. Scaled to 10K+ users.",
    website: midgenDomain,
    role: "Co-Founder & COO",
  },
  education: [
    {
      uni: "City University Bangladesh",
      program: "BSc in Computer Science & Engineering",
      year: "2022 - running",
      result: "3.75",
    },
    {
      uni: "Govt Bangla College",
      program: "BSc in Mathematics",
      year: "2018 - 2022",
      result: "3.20",
    },
  ],
  skills: {
    programmingLanguages: ["TypeScript", "JavaScript", "C++"],
    WebDev: ["Next.js", "React", "Node.js", "Express", "MongoDB", "PostgreSQL"],
    cloud: ["AWS", "Vercel", "Docker"],
    tools: ["Git", "GitHub", "Claude Code", "Cursor"],
    domains: ["AI/ML Integration", "SaaS Architecture", "System Design", "Team Management", "Operations", "Strategic Planning"],
  },
  projects: {
    project1: {
      title: "CPCCU Portal",
      date: "2024 - Present",
      description: "Club management platform for Competitive Programming Camp at City University, serving 500+ student members with contest management and resource sharing.",
      link: "https://cpccu.club",
      github: "https://github.com/cpccu/cpccu/",
      techStack: ["React", "Tailwind CSS", "Node.js", "MongoDB"],
      image: "https://i.ibb.co/n353KBb/cpccu.png",
      featured: true,
    },
    project2: {
      title: "Book Store MERN",
      date: "2024",
      description: "Full-stack e-commerce application with admin dashboard, cart functionality, and payment integration.",
      link: "",
      github: "https://github.com/mdsiaofficial/bookstore-project-mern",
      techStack: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
      image: "https://i.ibb.co/588FMXF/bookstore.png",
      featured: true,
    },
    project3: {
      title: "CRUD App MERN",
      date: "Aug 2024",
      description: "Production-ready CRUD application with RESTful API, authentication, and responsive admin dashboard.",
      link: "",
      github: "https://github.com/mdsiaofficial/crud-app-mern",
      techStack: ["React", "Node.js", "Express", "MongoDB"],
      image: "https://i.ibb.co/sWYTJ0v/crudapp.png",
      featured: false,
    },
    project4: {
      title: "Personal Portfolio",
      date: "2024",
      description: "Modern portfolio website showcasing projects, experience, and skills with responsive design.",
      link: "https://ashiq.pro.bd",
      github: "https://github.com/mdsiaofficial/ashiq-portfolio/",
      techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      image: "https://i.ibb.co/vJVwPYk/p1.png",
      featured: true,
    },
    project5: {
      title: "Positivus - Digital Marketing",
      date: "Jun 2024",
      description: "Landing page for digital marketing agency with modern UI and responsive design.",
      link: "https://positivus-frontend-react.vercel.app/",
      github: "https://github.com/mdsiaofficial/Positivus-Frontend-react/",
      techStack: ["React", "Tailwind CSS"],
      image: "https://i.ibb.co/9tKBBD6/p3.png",
      featured: false,
    },
    project6: {
      title: "AI Content Humanizer",
      date: "Jun 2024",
      description: "AI-powered tool to transform robotic text into natural, human-like content.",
      link: "https://humanize-frontend-design-react.vercel.app/",
      github: "https://github.com/mdsiaofficial/Humanize-Frontend-Design-React/",
      techStack: ["React", "Tailwind CSS", "OpenAI API"],
      image: "https://i.ibb.co/V2TxgVY/p2.png",
      featured: true,
    },
    project7: {
      title: "CRUD Data Table",
      date: "Jun 2024",
      description: "Interactive data table with create, read, update, delete operations and filtering.",
      link: "https://crud-data-table-project-reactjs.vercel.app/",
      github: "https://github.com/mdsiaofficial/CRUD-data-table-project-reactjs",
      techStack: ["React", "Tailwind CSS"],
      image: "https://i.ibb.co/jzypTmn/crud.png",
      featured: false,
    },
    project8: {
      title: "AI Company Website",
      date: "Jun 2024",
      description: "Modern landing page for AI company with service sections and animations.",
      link: "https://gpt-project-eosin.vercel.app/",
      github: "https://github.com/mdsiaofficial/gpt-project/",
      techStack: ["React", "Tailwind CSS"],
      image: "https://i.ibb.co/zNHSfp5/gpt.png",
      featured: false,
    },
    project9: {
      title: "Weather Dashboard",
      date: "Feb 2024",
      description: "Real-time weather application showing forecasts with beautiful UI and animations.",
      link: "https://mdsiaofficial.github.io/Weather-app/",
      github: "https://github.com/mdsiaofficial/Weather-app",
      techStack: ["HTML", "CSS", "JavaScript", "Weather API"],
      image: "https://i.ibb.co/Cz9fd34/weather.png",
      featured: false,
    },
    project10: {
      title: "Kanban Board",
      date: "Mar 2024",
      description: "Task management board with drag-and-drop functionality and task categorization.",
      link: "https://mdsiaofficial.github.io/Kanban_Board/",
      github: "https://github.com/mdsiaofficial/Kanban_Board",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/vC9mrj0/kanban.png",
      featured: false,
    },
    project11: {
      title: "Quiz Application",
      date: "Feb 2024",
      description: "Interactive quiz app with score tracking and multiple categories.",
      link: "https://mdsiaofficial.github.io/Quiz-App/",
      github: "https://github.com/mdsiaofficial/Quiz-App",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/4K79tqj/quiz.png",
      featured: false,
    },
    project12: {
      title: "Restaurant App UI",
      date: "Apr 2024",
      description: "Food delivery app interface with menu browsing and cart functionality.",
      link: "https://mdsiaofficial.github.io/Food-App/",
      github: "https://github.com/mdsiaofficial/Food-App",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/4R0K6gt/restaurant.png",
      featured: false,
    },
    project13: {
      title: "Todo Application",
      date: "Feb 2024",
      description: "Task management app with add, complete, and delete functionality.",
      link: "https://mdsiaofficial.github.io/Todo-app-for-org/",
      github: "https://github.com/mdsiaofficial/Todo-app-for-org/",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/850SYzP/todo.png",
      featured: false,
    },
    project14: {
      title: "Analog Clock",
      date: "Apr 2024",
      description: "Real-time analog clock with smooth animations and customizable themes.",
      link: "https://mdsiaofficial.github.io/Analog_Clock/",
      github: "https://github.com/mdsiaofficial/Analog_Clock",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/KGCptjx/analog.png",
      featured: false,
    },
    project15: {
      title: "Club Portal",
      date: "Apr 2024",
      description: "Clean university club website with event listings and member information.",
      link: "https://mdsiaofficial.github.io/Club-Portal/",
      github: "https://github.com/mdsiaofficial/Club-Portal",
      techStack: ["HTML", "CSS", "JavaScript"],
      image: "https://i.ibb.co/gTCp6Wx/club.png",
      featured: false,
    },
    project16: {
      title: "React Router Demo",
      date: "May 2024",
      description: "Practice project demonstrating React Router for multi-page navigation.",
      link: "https://react-router-project-nine-kappa.vercel.app/",
      github: "https://github.com/mdsiaofficial/react-router-project/",
      techStack: ["React", "React Router", "Tailwind CSS"],
      image: "https://i.ibb.co/ZTHZMqt/reactrouter.png",
      featured: false,
    },
    project17: {
      title: "Library Management System",
      date: "Dec 2025",
      description: "Practice project demonstrating React Router for multi-page navigation.",
      link: "https://library-cse416.netlify.app/",
      github: "https://github.com/mdsiaofficial/library-project/",
      techStack: ["React", "React Router", "Tailwind CSS"],
      image: "https://i.ibb.co/ZTHZMqt/reactrouter.png",
      featured: false,
    },
  },
  experiences: [
    {
      title: "Co-Founder & COO",
      company: "Midgen",
      date: "2024 - Present",
      responsibilities: "Leading overall operations, team management, and business strategy. Scaled platform to 10K+ active users. Overseeing product development, marketing, and customer success. Managing and leading development teams while driving revenue growth.",
      image: "https://i.ibb.co/SBJBTT3/atomic.png",
    },
    {
      title: "Junior Software Engineer",
      company: "Code Studio",
      date: "Nov 2024 - Present",
      responsibilities: "Building production-ready applications using React, Next.js, and MySQL. Collaborating with cross-functional teams to deliver enterprise solutions.",
      image: "https://i.ibb.co/SBJBTT3/atomic.png",
    },
    {
      title: "Former President",
      company: "City University Programming Club (CUPC)",
      date: "2024 - 2025",
      responsibilities: "Led the largest programming club at City University with 500+ members. Organized workshops, contests, and mentoring sessions. Developed leadership and event management skills.",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      title: "Former Co-Convenor",
      company: "BASIS Student Forum City University Chapter",
      date: "2024 - 2025",
      responsibilities: "Leading tech community initiatives and representing BASIS at university level. Built partnerships and organized industry events.",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
    {
      title: "Former President",
      company: "Competitive Programming Camp City University (CPCCU)",
      date: "2024 - 2025",
      responsibilities: "Organized training programs and contests to prepare students for ICPC. Managed a team of 20+ volunteers and coordinated events for 500+ participants.",
      image: "https://i.ibb.co/74Cx1KX/icpc.png",
    },
  ],
  achievements: [
    {
      title: "ACM ICPC - 2025",
      date: "Oct, 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest is an algorithmic programming contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      title: "ACM ICPC - 2024",
      date: "Oct, 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest is an algorithmic programming contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      title: "Meta Hacker Cup - 2024",
      date: "Oct, 2024",
      location: "Meta Coding Competitions, Facebook/Meta",
      description: "Hacker Cup is Meta's annual open programming competition. Open to participants around the world, we invite you to apply problem-solving and algorithmic coding skills to advance through each year's online rounds, win prizes, and have a chance to make it to the global finals and win the grand prize.",
      logo: "https://i.ibb.co/y5QQwH7/metahackercup.png",
      certificate: "https://i.ibb.co/fD7Jkg9/Meta-Hacker-Cup2023.jpg",
    },
    {
      title: "JavaScript Essential 1",
      date: "Jun, 2024",
      location: "",
      description: "Cisco Networking Academy provided JavaScript course",
      logo: "https://i.ibb.co/dfqYcvx/cisco.png",
      certificate: "https://i.ibb.co/BPsWXxb/Md-Shoriful-Islam-Java-Script-Essen-certificate.png",
    },
    {
      title: "ACM ICPC - 2023",
      date: "Oct, 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest is an algorithmic programming contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "https://i.ibb.co/Pt7wkmz/2024-ICPC-2023-Asia-Dhaka-Preli-Md-Shoriful-Islam-CHALLENGE.jpg",
    },
    {
      title: "Meta Hacker Cup - 2023",
      date: "Sept, 2023",
      location: "Meta Coding Competitions, Facebook/Meta",
      description: "Hacker Cup is Meta's annual open programming competition. Open to participants around the world, we invite you to apply problem-solving and algorithmic coding skills to advance through each year's online rounds, win prizes, and have a chance to make it to the global finals and win the grand prize.",
      logo: "https://i.ibb.co/y5QQwH7/metahackercup.png",
      certificate: "https://i.ibb.co/fD7Jkg9/Meta-Hacker-Cup2023.jpg",
    },
    {
      title: "ACM ICPC - 2022",
      date: "Mar, 2023",
      location: "City University Bangladesh",
      description: "The International Collegiate Programming Contest is an algorithmic programming contest for college students.",
      logo: "https://i.ibb.co/74Cx1KX/icpc.png",
      certificate: "",
    },
    {
      title: "23rd Intra University Programming Contest",
      date: "Oct, 2022",
      location: "City University",
      description: "Annual Programming Contest of algorithmic programming for students.",
      logo: "https://i.ibb.co/pQw9xhj/cityuni.png",
      certificate: "https://i.ibb.co/pQYDWPx/cupc2022.png",
    },
  ],
  socialLinks: {
    linkedin: "https://linkedin.com/in/mdsiaofficial",
    github: "https://github.com/mdsiaofficial",
    medium: "https://medium.com/@mdsiaofficial",
    email: "ashiq@midgen.ai",
    leetcode: "https://leetcode.com/mdsiaofficial",
    codeforces: "https://codeforces.com/profile/mdsiaofficial",
  },
};


export const stats = [
  { icon: FaUsers, label: "Active Users", value: "10K+" },
  { icon: FaUsers, label: "Team Members Led", value: "500+" },
  { icon: FaBuilding, label: "Companies Founded", value: "1" },
  { icon: FaTrophy, label: "Years Leadership", value: "3+" },
  { icon: FaRocket, label: "Products Launched", value: "4+" },
  { icon: FaLightbulb, label: "Years Experience", value: "5+" },
];

export const leadership = [
  {
    title: "Co-Founder & COO, Midgen",
    description: "Overseeing operations, strategy, and team growth - scaled to 10K+ users",
  },
  {
    title: "Former President, CUPC",
    description: "Led the largest programming club at City University with 500+ members",
  },
  {
    title: "Founding Convenor, OSSCCU",
    description: "Built and led Open Source Software Community from ground up",
  },
  {
    title: "Former Co-Convenor, BASIS Student Forum City University Chapter",
    description: "Driving tech community initiatives at university level",
  },
  {
    title: "Former President, CPCCU",
    description: "Led the largest Competitive Programming Camp at City University",
  },
];